- Function and "eval" feature
 - This would be hard... especially around memory and u+000c's STDIN...
 - Should it be removed altogether? I mean, functions can be simulated easily by a simple stack push, jump, and stack pop.
- Make more practical commands
- Make the interpreter code more clean
- Rewrite document so it is more specific, understandable, and unambiguous.